In [2]:
import numpy as np


In [3]:
a=np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [5]:
z=np.zeros((2,3))
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
r=np.arange(0,10,2)
r

array([0, 2, 4, 6, 8])

In [7]:
b=np.array([4,5,6])
a+b


array([5, 7, 9])

In [8]:
np.mean(a)

2.0

In [9]:
np.max(a)

3

In [10]:
np.min(a)

1

In [11]:
c=np.array([[1,2],[3,4]])

In [12]:
c

array([[1, 2],
       [3, 4]])

In [13]:
type(c)

numpy.ndarray

In [14]:
d=np.array([[4,8],[6,9]])
c+d

array([[ 5, 10],
       [ 9, 13]])

In [16]:
e=c*d
e

array([[ 4, 16],
       [18, 36]])

In [17]:
f=np.dot(c,d)
f

array([[16, 26],
       [36, 60]])

In [18]:
c.T

array([[1, 3],
       [2, 4]])

In [19]:
c

array([[1, 2],
       [3, 4]])

In [20]:
d

array([[4, 8],
       [6, 9]])

In [23]:
f=np.dot(c,d)
f

array([[16, 26],
       [36, 60]])

In [24]:
f.T

array([[16, 36],
       [26, 60]])

In [25]:
print("\n matrix 1:\n",c)
print("\n matrix 2:\n",d)
print("\n Addition:\n",c+d)
print("\n Substraction:\n",c-d)
print("\n Multiplication(element wise ):\n",c*d)
print("\n Dot Multiplication(row x column):\n",f)
print("\n Transpose:\n",f.T)


 matrix 1:
 [[1 2]
 [3 4]]

 matrix 2:
 [[4 8]
 [6 9]]

 Addition:
 [[ 5 10]
 [ 9 13]]

 Substraction:
 [[-3 -6]
 [-3 -5]]

 Multiplication(element wise ):
 [[ 4 16]
 [18 36]]

 Dot Multiplication(row x column):
 [[16 26]
 [36 60]]

 Transpose:
 [[16 36]
 [26 60]]
